# Generated by copilot, verified correct
from typing import List

class Solution:
    def subsets(self, nums: List[int]) -> List[List[int]]:
        power_set = [[]]

        # For nums=[1,2,3], power_set will evolve like this
        # [[], [1]]
        # [[], [1], [2], [1, 2]]
        # [[], [1], [2], [1, 2], [3], [1, 3], [2, 3], [1, 2, 3]]
        for num in nums:
            power_set += [curr + [num] for curr in power_set]
        
        return power_set

